# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concrete_crypto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import crypto_pb2 as crypto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='concrete_crypto.proto',
  package='meerkat',
  syntax='proto3',
  serialized_pb=_b('\n\x15\x63oncrete_crypto.proto\x12\x07meerkat\x1a\x0c\x63rypto.proto\"3\n\x10\x45lGamalPublicKey\x12\x1f\n\x17subject_public_key_info\x18\x01 \x01(\x0c\"\x1c\n\x0cGroupElement\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"Y\n\x11\x45lGamalCiphertext\x12!\n\x02\x63\x31\x18\x01 \x01(\x0b\x32\x15.meerkat.GroupElement\x12!\n\x02\x63\x32\x18\x02 \x01(\x0b\x32\x15.meerkat.GroupElementB\x12\n\x10meerkat.protobufb\x06proto3')
  ,
  dependencies=[crypto__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ELGAMALPUBLICKEY = _descriptor.Descriptor(
  name='ElGamalPublicKey',
  full_name='meerkat.ElGamalPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject_public_key_info', full_name='meerkat.ElGamalPublicKey.subject_public_key_info', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=99,
)


_GROUPELEMENT = _descriptor.Descriptor(
  name='GroupElement',
  full_name='meerkat.GroupElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.GroupElement.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=129,
)


_ELGAMALCIPHERTEXT = _descriptor.Descriptor(
  name='ElGamalCiphertext',
  full_name='meerkat.ElGamalCiphertext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c1', full_name='meerkat.ElGamalCiphertext.c1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c2', full_name='meerkat.ElGamalCiphertext.c2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=220,
)

_ELGAMALCIPHERTEXT.fields_by_name['c1'].message_type = _GROUPELEMENT
_ELGAMALCIPHERTEXT.fields_by_name['c2'].message_type = _GROUPELEMENT
DESCRIPTOR.message_types_by_name['ElGamalPublicKey'] = _ELGAMALPUBLICKEY
DESCRIPTOR.message_types_by_name['GroupElement'] = _GROUPELEMENT
DESCRIPTOR.message_types_by_name['ElGamalCiphertext'] = _ELGAMALCIPHERTEXT

ElGamalPublicKey = _reflection.GeneratedProtocolMessageType('ElGamalPublicKey', (_message.Message,), dict(
  DESCRIPTOR = _ELGAMALPUBLICKEY,
  __module__ = 'concrete_crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.ElGamalPublicKey)
  ))
_sym_db.RegisterMessage(ElGamalPublicKey)

GroupElement = _reflection.GeneratedProtocolMessageType('GroupElement', (_message.Message,), dict(
  DESCRIPTOR = _GROUPELEMENT,
  __module__ = 'concrete_crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.GroupElement)
  ))
_sym_db.RegisterMessage(GroupElement)

ElGamalCiphertext = _reflection.GeneratedProtocolMessageType('ElGamalCiphertext', (_message.Message,), dict(
  DESCRIPTOR = _ELGAMALCIPHERTEXT,
  __module__ = 'concrete_crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.ElGamalCiphertext)
  ))
_sym_db.RegisterMessage(ElGamalCiphertext)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020meerkat.protobuf'))
# @@protoc_insertion_point(module_scope)
