# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crypto.proto',
  package='meerkat',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63rypto.proto\x12\x07meerkat\"\x1a\n\nBigInteger\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"R\n\tSignature\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.meerkat.SignatureType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x11\n\tsigner_id\x18\x03 \x01(\x0c\"N\n\x18SignatureVerificationKey\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.meerkat.SignatureType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"#\n\x13\x45ncryptionPublicKey\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x14\x45ncryptionRandomness\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\")\n\x19RandomnessGenerationProof\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\".\n\x1eRerandomizableEncryptedMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c*#\n\rSignatureType\x12\t\n\x05\x45\x43\x44SA\x10\x00\x12\x07\n\x03\x44SA\x10\x01\x42\x12\n\x10meerkat.protobufb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SIGNATURETYPE = _descriptor.EnumDescriptor(
  name='SignatureType',
  full_name='meerkat.SignatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ECDSA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSA', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=383,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_SIGNATURETYPE)

SignatureType = enum_type_wrapper.EnumTypeWrapper(_SIGNATURETYPE)
ECDSA = 0
DSA = 1



_BIGINTEGER = _descriptor.Descriptor(
  name='BigInteger',
  full_name='meerkat.BigInteger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.BigInteger.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=51,
)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='meerkat.Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='meerkat.Signature.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.Signature.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signer_id', full_name='meerkat.Signature.signer_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=135,
)


_SIGNATUREVERIFICATIONKEY = _descriptor.Descriptor(
  name='SignatureVerificationKey',
  full_name='meerkat.SignatureVerificationKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='meerkat.SignatureVerificationKey.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.SignatureVerificationKey.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=215,
)


_ENCRYPTIONPUBLICKEY = _descriptor.Descriptor(
  name='EncryptionPublicKey',
  full_name='meerkat.EncryptionPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.EncryptionPublicKey.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=252,
)


_ENCRYPTIONRANDOMNESS = _descriptor.Descriptor(
  name='EncryptionRandomness',
  full_name='meerkat.EncryptionRandomness',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.EncryptionRandomness.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=290,
)


_RANDOMNESSGENERATIONPROOF = _descriptor.Descriptor(
  name='RandomnessGenerationProof',
  full_name='meerkat.RandomnessGenerationProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.RandomnessGenerationProof.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=333,
)


_RERANDOMIZABLEENCRYPTEDMESSAGE = _descriptor.Descriptor(
  name='RerandomizableEncryptedMessage',
  full_name='meerkat.RerandomizableEncryptedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.RerandomizableEncryptedMessage.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=381,
)

_SIGNATURE.fields_by_name['type'].enum_type = _SIGNATURETYPE
_SIGNATUREVERIFICATIONKEY.fields_by_name['type'].enum_type = _SIGNATURETYPE
DESCRIPTOR.message_types_by_name['BigInteger'] = _BIGINTEGER
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE
DESCRIPTOR.message_types_by_name['SignatureVerificationKey'] = _SIGNATUREVERIFICATIONKEY
DESCRIPTOR.message_types_by_name['EncryptionPublicKey'] = _ENCRYPTIONPUBLICKEY
DESCRIPTOR.message_types_by_name['EncryptionRandomness'] = _ENCRYPTIONRANDOMNESS
DESCRIPTOR.message_types_by_name['RandomnessGenerationProof'] = _RANDOMNESSGENERATIONPROOF
DESCRIPTOR.message_types_by_name['RerandomizableEncryptedMessage'] = _RERANDOMIZABLEENCRYPTEDMESSAGE
DESCRIPTOR.enum_types_by_name['SignatureType'] = _SIGNATURETYPE

BigInteger = _reflection.GeneratedProtocolMessageType('BigInteger', (_message.Message,), dict(
  DESCRIPTOR = _BIGINTEGER,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.BigInteger)
  ))
_sym_db.RegisterMessage(BigInteger)

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURE,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.Signature)
  ))
_sym_db.RegisterMessage(Signature)

SignatureVerificationKey = _reflection.GeneratedProtocolMessageType('SignatureVerificationKey', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATUREVERIFICATIONKEY,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.SignatureVerificationKey)
  ))
_sym_db.RegisterMessage(SignatureVerificationKey)

EncryptionPublicKey = _reflection.GeneratedProtocolMessageType('EncryptionPublicKey', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTIONPUBLICKEY,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.EncryptionPublicKey)
  ))
_sym_db.RegisterMessage(EncryptionPublicKey)

EncryptionRandomness = _reflection.GeneratedProtocolMessageType('EncryptionRandomness', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTIONRANDOMNESS,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.EncryptionRandomness)
  ))
_sym_db.RegisterMessage(EncryptionRandomness)

RandomnessGenerationProof = _reflection.GeneratedProtocolMessageType('RandomnessGenerationProof', (_message.Message,), dict(
  DESCRIPTOR = _RANDOMNESSGENERATIONPROOF,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.RandomnessGenerationProof)
  ))
_sym_db.RegisterMessage(RandomnessGenerationProof)

RerandomizableEncryptedMessage = _reflection.GeneratedProtocolMessageType('RerandomizableEncryptedMessage', (_message.Message,), dict(
  DESCRIPTOR = _RERANDOMIZABLEENCRYPTEDMESSAGE,
  __module__ = 'crypto_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.RerandomizableEncryptedMessage)
  ))
_sym_db.RegisterMessage(RerandomizableEncryptedMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020meerkat.protobuf'))
# @@protoc_insertion_point(module_scope)
