# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mixing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import crypto_pb2 as crypto__pb2
import concrete_crypto_pb2 as concrete__crypto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mixing.proto',
  package='meerkat',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmixing.proto\x12\x07meerkat\x1a\x0c\x63rypto.proto\x1a\x15\x63oncrete_crypto.proto\".\n\x0eMixBatchHeader\x12\x0c\n\x04logN\x18\x01 \x01(\x05\x12\x0e\n\x06layers\x18\x02 \x01(\x05\"\x19\n\tPlaintext\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xd6\x07\n\tMix2Proof\x12\x35\n\x0c\x66irstMessage\x18\x01 \x01(\x0b\x32\x1f.meerkat.Mix2Proof.FirstMessage\x12\x35\n\x0c\x66inalMessage\x18\x02 \x01(\x0b\x32\x1f.meerkat.Mix2Proof.FinalMessage\x12-\n\x08location\x18\x05 \x01(\x0b\x32\x1b.meerkat.Mix2Proof.Location\x1a\x93\x01\n\tDlogProof\x1aT\n\x0c\x46irstMessage\x12!\n\x02gr\x18\x01 \x01(\x0b\x32\x15.meerkat.GroupElement\x12!\n\x02hr\x18\x02 \x01(\x0b\x32\x15.meerkat.GroupElement\x1a\x30\n\x0c\x46inalMessage\x12 \n\x03xcr\x18\x01 \x01(\x0b\x32\x13.meerkat.BigInteger\x1a\x9c\x02\n\x08\x41ndProof\x1a\x86\x01\n\x0c\x46irstMessage\x12:\n\x07\x63lause0\x18\x01 \x01(\x0b\x32).meerkat.Mix2Proof.DlogProof.FirstMessage\x12:\n\x07\x63lause1\x18\x02 \x01(\x0b\x32).meerkat.Mix2Proof.DlogProof.FirstMessage\x1a\x86\x01\n\x0c\x46inalMessage\x12:\n\x07\x63lause0\x18\x01 \x01(\x0b\x32).meerkat.Mix2Proof.DlogProof.FinalMessage\x12:\n\x07\x63lause1\x18\x02 \x01(\x0b\x32).meerkat.Mix2Proof.DlogProof.FinalMessage\x1a\x84\x01\n\x0c\x46irstMessage\x12\x39\n\x07\x63lause0\x18\x01 \x01(\x0b\x32(.meerkat.Mix2Proof.AndProof.FirstMessage\x12\x39\n\x07\x63lause1\x18\x02 \x01(\x0b\x32(.meerkat.Mix2Proof.AndProof.FirstMessage\x1a\xa5\x01\n\x0c\x46inalMessage\x12\x39\n\x07\x63lause0\x18\x01 \x01(\x0b\x32(.meerkat.Mix2Proof.AndProof.FinalMessage\x12\x39\n\x07\x63lause1\x18\x02 \x01(\x0b\x32(.meerkat.Mix2Proof.AndProof.FinalMessage\x12\x1f\n\x02\x63\x30\x18\x03 \x01(\x0b\x32\x13.meerkat.BigInteger\x1aH\n\x08Location\x12\r\n\x05layer\x18\x01 \x01(\x05\x12\x11\n\tswitchIdx\x18\x02 \x01(\x05\x12\x0c\n\x04out0\x18\x03 \x01(\x05\x12\x0c\n\x04out1\x18\x04 \x01(\x05\x42\x12\n\x10meerkat.protobufb\x06proto3')
  ,
  dependencies=[crypto__pb2.DESCRIPTOR,concrete__crypto__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MIXBATCHHEADER = _descriptor.Descriptor(
  name='MixBatchHeader',
  full_name='meerkat.MixBatchHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logN', full_name='meerkat.MixBatchHeader.logN', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layers', full_name='meerkat.MixBatchHeader.layers', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=108,
)


_PLAINTEXT = _descriptor.Descriptor(
  name='Plaintext',
  full_name='meerkat.Plaintext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='meerkat.Plaintext.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=135,
)


_MIX2PROOF_DLOGPROOF_FIRSTMESSAGE = _descriptor.Descriptor(
  name='FirstMessage',
  full_name='meerkat.Mix2Proof.DlogProof.FirstMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gr', full_name='meerkat.Mix2Proof.DlogProof.FirstMessage.gr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hr', full_name='meerkat.Mix2Proof.DlogProof.FirstMessage.hr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=406,
)

_MIX2PROOF_DLOGPROOF_FINALMESSAGE = _descriptor.Descriptor(
  name='FinalMessage',
  full_name='meerkat.Mix2Proof.DlogProof.FinalMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xcr', full_name='meerkat.Mix2Proof.DlogProof.FinalMessage.xcr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=456,
)

_MIX2PROOF_DLOGPROOF = _descriptor.Descriptor(
  name='DlogProof',
  full_name='meerkat.Mix2Proof.DlogProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_MIX2PROOF_DLOGPROOF_FIRSTMESSAGE, _MIX2PROOF_DLOGPROOF_FINALMESSAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=456,
)

_MIX2PROOF_ANDPROOF_FIRSTMESSAGE = _descriptor.Descriptor(
  name='FirstMessage',
  full_name='meerkat.Mix2Proof.AndProof.FirstMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clause0', full_name='meerkat.Mix2Proof.AndProof.FirstMessage.clause0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clause1', full_name='meerkat.Mix2Proof.AndProof.FirstMessage.clause1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=606,
)

_MIX2PROOF_ANDPROOF_FINALMESSAGE = _descriptor.Descriptor(
  name='FinalMessage',
  full_name='meerkat.Mix2Proof.AndProof.FinalMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clause0', full_name='meerkat.Mix2Proof.AndProof.FinalMessage.clause0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clause1', full_name='meerkat.Mix2Proof.AndProof.FinalMessage.clause1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=743,
)

_MIX2PROOF_ANDPROOF = _descriptor.Descriptor(
  name='AndProof',
  full_name='meerkat.Mix2Proof.AndProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_MIX2PROOF_ANDPROOF_FIRSTMESSAGE, _MIX2PROOF_ANDPROOF_FINALMESSAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=743,
)

_MIX2PROOF_FIRSTMESSAGE = _descriptor.Descriptor(
  name='FirstMessage',
  full_name='meerkat.Mix2Proof.FirstMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clause0', full_name='meerkat.Mix2Proof.FirstMessage.clause0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clause1', full_name='meerkat.Mix2Proof.FirstMessage.clause1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=878,
)

_MIX2PROOF_FINALMESSAGE = _descriptor.Descriptor(
  name='FinalMessage',
  full_name='meerkat.Mix2Proof.FinalMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clause0', full_name='meerkat.Mix2Proof.FinalMessage.clause0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clause1', full_name='meerkat.Mix2Proof.FinalMessage.clause1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c0', full_name='meerkat.Mix2Proof.FinalMessage.c0', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=881,
  serialized_end=1046,
)

_MIX2PROOF_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='meerkat.Mix2Proof.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer', full_name='meerkat.Mix2Proof.Location.layer', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='switchIdx', full_name='meerkat.Mix2Proof.Location.switchIdx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out0', full_name='meerkat.Mix2Proof.Location.out0', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out1', full_name='meerkat.Mix2Proof.Location.out1', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1048,
  serialized_end=1120,
)

_MIX2PROOF = _descriptor.Descriptor(
  name='Mix2Proof',
  full_name='meerkat.Mix2Proof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstMessage', full_name='meerkat.Mix2Proof.firstMessage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finalMessage', full_name='meerkat.Mix2Proof.finalMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='meerkat.Mix2Proof.location', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MIX2PROOF_DLOGPROOF, _MIX2PROOF_ANDPROOF, _MIX2PROOF_FIRSTMESSAGE, _MIX2PROOF_FINALMESSAGE, _MIX2PROOF_LOCATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=1120,
)

_MIX2PROOF_DLOGPROOF_FIRSTMESSAGE.fields_by_name['gr'].message_type = concrete__crypto__pb2._GROUPELEMENT
_MIX2PROOF_DLOGPROOF_FIRSTMESSAGE.fields_by_name['hr'].message_type = concrete__crypto__pb2._GROUPELEMENT
_MIX2PROOF_DLOGPROOF_FIRSTMESSAGE.containing_type = _MIX2PROOF_DLOGPROOF
_MIX2PROOF_DLOGPROOF_FINALMESSAGE.fields_by_name['xcr'].message_type = crypto__pb2._BIGINTEGER
_MIX2PROOF_DLOGPROOF_FINALMESSAGE.containing_type = _MIX2PROOF_DLOGPROOF
_MIX2PROOF_DLOGPROOF.containing_type = _MIX2PROOF
_MIX2PROOF_ANDPROOF_FIRSTMESSAGE.fields_by_name['clause0'].message_type = _MIX2PROOF_DLOGPROOF_FIRSTMESSAGE
_MIX2PROOF_ANDPROOF_FIRSTMESSAGE.fields_by_name['clause1'].message_type = _MIX2PROOF_DLOGPROOF_FIRSTMESSAGE
_MIX2PROOF_ANDPROOF_FIRSTMESSAGE.containing_type = _MIX2PROOF_ANDPROOF
_MIX2PROOF_ANDPROOF_FINALMESSAGE.fields_by_name['clause0'].message_type = _MIX2PROOF_DLOGPROOF_FINALMESSAGE
_MIX2PROOF_ANDPROOF_FINALMESSAGE.fields_by_name['clause1'].message_type = _MIX2PROOF_DLOGPROOF_FINALMESSAGE
_MIX2PROOF_ANDPROOF_FINALMESSAGE.containing_type = _MIX2PROOF_ANDPROOF
_MIX2PROOF_ANDPROOF.containing_type = _MIX2PROOF
_MIX2PROOF_FIRSTMESSAGE.fields_by_name['clause0'].message_type = _MIX2PROOF_ANDPROOF_FIRSTMESSAGE
_MIX2PROOF_FIRSTMESSAGE.fields_by_name['clause1'].message_type = _MIX2PROOF_ANDPROOF_FIRSTMESSAGE
_MIX2PROOF_FIRSTMESSAGE.containing_type = _MIX2PROOF
_MIX2PROOF_FINALMESSAGE.fields_by_name['clause0'].message_type = _MIX2PROOF_ANDPROOF_FINALMESSAGE
_MIX2PROOF_FINALMESSAGE.fields_by_name['clause1'].message_type = _MIX2PROOF_ANDPROOF_FINALMESSAGE
_MIX2PROOF_FINALMESSAGE.fields_by_name['c0'].message_type = crypto__pb2._BIGINTEGER
_MIX2PROOF_FINALMESSAGE.containing_type = _MIX2PROOF
_MIX2PROOF_LOCATION.containing_type = _MIX2PROOF
_MIX2PROOF.fields_by_name['firstMessage'].message_type = _MIX2PROOF_FIRSTMESSAGE
_MIX2PROOF.fields_by_name['finalMessage'].message_type = _MIX2PROOF_FINALMESSAGE
_MIX2PROOF.fields_by_name['location'].message_type = _MIX2PROOF_LOCATION
DESCRIPTOR.message_types_by_name['MixBatchHeader'] = _MIXBATCHHEADER
DESCRIPTOR.message_types_by_name['Plaintext'] = _PLAINTEXT
DESCRIPTOR.message_types_by_name['Mix2Proof'] = _MIX2PROOF

MixBatchHeader = _reflection.GeneratedProtocolMessageType('MixBatchHeader', (_message.Message,), dict(
  DESCRIPTOR = _MIXBATCHHEADER,
  __module__ = 'mixing_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.MixBatchHeader)
  ))
_sym_db.RegisterMessage(MixBatchHeader)

Plaintext = _reflection.GeneratedProtocolMessageType('Plaintext', (_message.Message,), dict(
  DESCRIPTOR = _PLAINTEXT,
  __module__ = 'mixing_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.Plaintext)
  ))
_sym_db.RegisterMessage(Plaintext)

Mix2Proof = _reflection.GeneratedProtocolMessageType('Mix2Proof', (_message.Message,), dict(

  DlogProof = _reflection.GeneratedProtocolMessageType('DlogProof', (_message.Message,), dict(

    FirstMessage = _reflection.GeneratedProtocolMessageType('FirstMessage', (_message.Message,), dict(
      DESCRIPTOR = _MIX2PROOF_DLOGPROOF_FIRSTMESSAGE,
      __module__ = 'mixing_pb2'
      # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.DlogProof.FirstMessage)
      ))
    ,

    FinalMessage = _reflection.GeneratedProtocolMessageType('FinalMessage', (_message.Message,), dict(
      DESCRIPTOR = _MIX2PROOF_DLOGPROOF_FINALMESSAGE,
      __module__ = 'mixing_pb2'
      # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.DlogProof.FinalMessage)
      ))
    ,
    DESCRIPTOR = _MIX2PROOF_DLOGPROOF,
    __module__ = 'mixing_pb2'
    # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.DlogProof)
    ))
  ,

  AndProof = _reflection.GeneratedProtocolMessageType('AndProof', (_message.Message,), dict(

    FirstMessage = _reflection.GeneratedProtocolMessageType('FirstMessage', (_message.Message,), dict(
      DESCRIPTOR = _MIX2PROOF_ANDPROOF_FIRSTMESSAGE,
      __module__ = 'mixing_pb2'
      # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.AndProof.FirstMessage)
      ))
    ,

    FinalMessage = _reflection.GeneratedProtocolMessageType('FinalMessage', (_message.Message,), dict(
      DESCRIPTOR = _MIX2PROOF_ANDPROOF_FINALMESSAGE,
      __module__ = 'mixing_pb2'
      # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.AndProof.FinalMessage)
      ))
    ,
    DESCRIPTOR = _MIX2PROOF_ANDPROOF,
    __module__ = 'mixing_pb2'
    # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.AndProof)
    ))
  ,

  FirstMessage = _reflection.GeneratedProtocolMessageType('FirstMessage', (_message.Message,), dict(
    DESCRIPTOR = _MIX2PROOF_FIRSTMESSAGE,
    __module__ = 'mixing_pb2'
    # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.FirstMessage)
    ))
  ,

  FinalMessage = _reflection.GeneratedProtocolMessageType('FinalMessage', (_message.Message,), dict(
    DESCRIPTOR = _MIX2PROOF_FINALMESSAGE,
    __module__ = 'mixing_pb2'
    # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.FinalMessage)
    ))
  ,

  Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
    DESCRIPTOR = _MIX2PROOF_LOCATION,
    __module__ = 'mixing_pb2'
    # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof.Location)
    ))
  ,
  DESCRIPTOR = _MIX2PROOF,
  __module__ = 'mixing_pb2'
  # @@protoc_insertion_point(class_scope:meerkat.Mix2Proof)
  ))
_sym_db.RegisterMessage(Mix2Proof)
_sym_db.RegisterMessage(Mix2Proof.DlogProof)
_sym_db.RegisterMessage(Mix2Proof.DlogProof.FirstMessage)
_sym_db.RegisterMessage(Mix2Proof.DlogProof.FinalMessage)
_sym_db.RegisterMessage(Mix2Proof.AndProof)
_sym_db.RegisterMessage(Mix2Proof.AndProof.FirstMessage)
_sym_db.RegisterMessage(Mix2Proof.AndProof.FinalMessage)
_sym_db.RegisterMessage(Mix2Proof.FirstMessage)
_sym_db.RegisterMessage(Mix2Proof.FinalMessage)
_sym_db.RegisterMessage(Mix2Proof.Location)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020meerkat.protobuf'))
# @@protoc_insertion_point(module_scope)
